### ISSUE TITLE
这个是真实KEY么？

### ISSUE THREAD

**Issue by hstarorg** [songxiaoliang/react-native-share#10]
https://github.com/songxiaoliang/react-native-share/blob/master/android/app/src/main/java/com/reactnativeshare/MainApplication.java

**Comment by songxiaoliang** [comment]
@hstarorg 嗯，这些key要换成你自己申请的。具体看各平台app信息即可。

**Comment by hstarorg** [comment]
哈哈，我是说这玩意最好不要提交到github上来。

**Comment by songxiaoliang** [comment]
@hstarorg 哈哈，多谢提醒，其实没关系啦~~

**Comment by hstarorg** [comment]
测试key就没啥，线上key，就容易悲剧。

**Comment by songxiaoliang** [comment]
@hstarorg 毋庸置疑，这肯定是测试key了~~

**Comment by songxiaoliang** [comment]
@hstarorg 今天会在该库集成第三方登录功能，可以持续关注一下。

**Comment by hstarorg** [comment]
@songxiaoliang 谢谢，马上会接手一个RN项目，希望能用得上。

**Comment by songxiaoliang** [comment]
@hstarorg 公司项目有还是私人项目？563609104 我QQ

**Comment by hstarorg** [comment]
@songxiaoliang 公司项目的，已加。
