### ISSUE TITLE
SharePackage.java文件报错

### ISSUE THREAD

**Issue by ding-love-yu** [songxiaoliang/react-native-share#12]
我RN版本50
SharePackage.java文件报错：method does not override a method from its superclass

`public class SharePackage implements ReactPackage {

    @Override
    public List<NativeModule> createNativeModules(ReactApplicationContext reactContext) {
        List<NativeModule> modules = new ArrayList<>();
        modules.add(new ShareModule(reactContext));
        return modules;
    }

    @Override
    public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    }

    @Override
    public List<ViewManager> createViewManagers(ReactApplicationContext reactContext) {
        return Collections.emptyList();
    }
}`

**Comment by songxiaoliang** [comment]
@ding-love-yu 将  createJSModules 这个方法删除即可。

**Comment by shuiRong** [comment]
@songxiaoliang 文档说`则需要将module文件夹中ShareModule类中的createJSModule方法删除即可。`
但似乎应该是在`SharePackage.java`里，建议更新下文档。
