### ISSUE TITLE
微信，微博能呼起授权，QQ不行

### ISSUE THREAD

**Issue by moxiaonai** [songxiaoliang/react-native-share#16]
模拟器报错如图示，什么问题啊
![image](https://user-images.githubusercontent.com/13172934/33758635-f3d0f096-dc39-11e7-8b7c-5b1eec9e807d.png)

**Comment by moxiaonai** [comment]
我自己的问题，没PlatformConfig.setQQZone(）我以为这个只是设置QQ空间的就给注掉了，查了文档才知道，qq跟qq空间用的同一个

**Comment by songxiaoliang** [comment]
@moxiaonai 对的，QQ和Qzone是同一个key、AppSecret。

**Comment by moxiaonai** [comment]
@songxiaoliang 我qq授权后程序闪退是什么问题，app没有在qq开放平台提交，没用通过审核，qq开放平台添加了协同者账号。
![image](https://user-images.githubusercontent.com/13172934/33815031-52363e3a-de69-11e7-8fa2-2227935aa43d.png)

**Comment by moxiaonai** [comment]
@songxiaoliang ![](https://ws1.sinaimg.cn/large/e01d8d94ly1fmcom6pavmj20sj0eo75l.jpg)

**Comment by moxiaonai** [comment]
给模拟器装了qq，调起授权的话提示给官方在正版应用，大概知道是什么问题了
