### ISSUE TITLE
配置Android启动崩溃

### ISSUE THREAD

**Issue by shiyunsheng** [songxiaoliang/react-native-share#17]
所有的配置都是按照网页上的步骤操作的。目前只配置了安卓。运行直接崩溃。
错误日志： Module AppRegistry is not a registered callable module (calling runApplication)
查了资料。也更新了gradlew .
cd android
sudo ./gradlew clean 还是出现。。

**Comment by shiyunsheng** [comment]
我估计不是插件的问题。因为我现在把所有的插件信息都删掉了。还是报这个错误。
我还是慢慢整一下。找到结果。我在留言说一下。

**Comment by shiyunsheng** [comment]
找到原因了。在MainApplication里。我开始看到BuildConfig报错。就导入了import com.facebook.react.BuildConfig;就因为这个报了上面的错误。。这里是不需要导入包的。希望对后面的朋友有帮助。

**Comment by songxiaoliang** [comment]
@shiyunsheng BuildConfig肯定是要自己项目的哦，没有其他问题，我先关闭issue啦
