### ISSUE TITLE
回调的返回信息不太符合规则

### ISSUE THREAD

**Issue by zhuangdize** [songxiaoliang/react-native-share#2]
![image](https://user-images.githubusercontent.com/10000643/29709955-03592c8e-89c1-11e7-8bba-0414bc3833bb.png)
![image](https://user-images.githubusercontent.com/10000643/29709960-0931d714-89c1-11e7-8baf-5ffd31b98ca9.png)

问题描述：
1. 当使用微信分享 失败的时候  code 返回却是字符串类型的错误信息，
希望能够返回一个对象，比如： { code: 500 , msg: '没有安装应用' }）

2. message 返回的结果是 undefined。

请问如何解决

**Comment by songxiaoliang** [comment]
@zhuangdize 请问是Android还是IOS？

**Comment by zhuangdize** [comment]
@songxiaoliang  Android

**Comment by songxiaoliang** [comment]
@zhuangdize Android修改ShareModule.java文集即可。
