### ISSUE TITLE
找不到这个包com.umeng.commonsdk.stateless.UMSLEnvelopeBuild;

### ISSUE THREAD

**Issue by Run-Snail** [songxiaoliang/react-native-share#26]
![iz67 c9h7 ci g 3 qh4bf](https://user-images.githubusercontent.com/20348904/39849824-c836e7f4-5440-11e8-973c-21f04e71d928.png)
这个文件中 import com.umeng.commonsdk.stateless.UMSLEnvelopeBuild; 这个包找不到
![ii oi7 n 9hw cg 7vbf hl](https://user-images.githubusercontent.com/20348904/39849841-f0c20078-5440-11e8-9292-68c5a3736a8a.png)

**Comment by songxiaoliang** [comment]
@Run-Snail 确定下sdk版本是否用的相同的。
