### ISSUE TITLE
程序包com.d3o.sharemodule.utils不存在

### ISSUE THREAD

**Issue by ranxudong** [songxiaoliang/react-native-share#28]
D:\React-native\day201805016\android\app\src\main\java\com\day201805016\module\ShareModule.java:13: 错误: 程序包com.d3o 不存在
import com.d3o.R;
              
D:\React-native\day201805016\android\app\src\main\java\com\day201805016\module\ShareModule.java:14: 错误: 程序包com.d3o.sharemodule.utils不存在
import com.d3o.sharemodule.utils.BitMapUtil;
                                ^
  ##D:\React-native\day201805016\android\app\src\main\java\com\day201805016\module\ShareModule.java:70: 错误: 找不到符号
            Bitmap img = BitmapFactory.decodeFile(BitMapUtil.getImageAbsolutePath(mActivity, Uri.parse(imgPath)));
                                                  ^
  符号:   变量 BitMapUtil
  位置: 类 ShareModule
D:\React-native\day201805016\android\app\src\main\java\com\day201805016\module\ShareModule.java:71: 错误: 找不到符号
            final UMImage image = new UMImage(mActivity, BitMapUtil.ImageCompress(img));
                                                         ^
  符号:   变量 BitMapUtil
  位置: 类 ShareModule
D:\React-native\day201805016\android\app\src\main\java\com\day201805016\module\SharePackage.java:26: 错误: 方法不会覆盖 或实现超类型的方法
    @Override
    ^
5 个错误
:app:compileDebugJavaWithJavac FAILED

**Comment by songxiaoliang** [comment]
@ranxudong import com.d3o.R，d3o修改成自己的包名。

**Comment by ranxudong** [comment]
@songxiaoliang  




![1](https://user-images.githubusercontent.com/15652154/40290483-d6bbd3f8-5cf0-11e8-87a0-4a7cad35e46c.png)
![2](https://user-images.githubusercontent.com/15652154/40290491-e077339c-5cf0-11e8-8a34-aa65f1ffa13a.jpg)
