### ISSUE TITLE
UMSocialCore.h文件找不到

### ISSUE THREAD

**Issue by japinli** [songxiaoliang/react-native-share#3]
大神， 我按照你给的步骤做完后运行项目报错，说是UMSocialCore／UMSocialCore.h这个没有找到，是哪一步配置除了问题呢？（ios）
![image](https://user-images.githubusercontent.com/20606090/30115099-5137a1da-934c-11e7-915d-1d2b6de76067.png)

**Comment by songxiaoliang** [comment]
@japinl 这个是友盟的SDK，你先确定下SDK配置是否正确了。如果确定正确的情况下，将<>改成引号试试

**Comment by japinli** [comment]
这个是我第一步配置出错了，已经解决了。thank you

**Comment by songxiaoliang** [comment]
@japinl 好的，没有问题的话，那我先把issue关闭了哈~
