### ISSUE TITLE
 错误: 程序包com.d3o不存在 import com.d3o.R; 程序包com.d3o.sharemodule.utils;不存在

### ISSUE THREAD

**Issue by showtan001** [songxiaoliang/react-native-share#34]
这怎么办？ rn 0.51.0

error:

`:app:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed,
no previous execution, etc.).
E:\new\jordina\android\app\src\main\java\com\xxx\module\ShareModule.java:13:
 错误: 程序包com.d3o不存在
import com.d3o.R;
              ^
E:\new\jordina\android\app\src\main\java\com\xxx\module\ShareModule.java:14:
 错误: 程序包com.d3o.sharemodule.utils不存在
import com.d3o.sharemodule.utils.BitMapUtil;
                                ^
E:\new\jordina\android\app\src\main\java\com\xxx\MainApplication.java:92: 错
误: 找不到符号
    UMConfigure.init(this,"5ab0cd77f43e48580000001f","umeng",UMConfigure.DEVICE_
TYPE_PHONE,"");
                                                             ^
  符号:   变量 UMConfigure
  位置: 类 MainApplication
E:\new\jordina\android\app\src\main\java\com\xxx\MainApplication.java:92: 错
误: 找不到符号
    UMConfigure.init(this,"5ab0cd77f43e48580000001f","umeng",UMConfigure.DEVICE_
TYPE_PHONE,"");
    ^
  符号:   变量 UMConfigure
  位置: 类 MainApplication
E:\new\jordina\android\app\src\main\java\com\xxx\module\ShareModule.java:68:
 错误: 找不到符号
            Bitmap img = BitmapFactory.decodeFile(BitMapUtil.getImageAbsolutePat
h(mActivity, Uri.parse(imgPath)));
                                                  ^
  符号:   变量 BitMapUtil
  位置: 类 ShareModule
E:\new\jordina\android\app\src\main\java\com\xxx\module\ShareModule.java:69:
 错误: 找不到符号
            final UMImage image = new UMImage(mActivity, BitMapUtil.ImageCompres
s(img));
                                                         ^
  符号:   变量 BitMapUtil
  位置: 类 ShareModule
6 个错误
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 1 mins 16.91 secs
`

**Comment by andyhuai** [comment]
怎么解决的？

**Comment by songxiaoliang** [comment]
@andyhuai 包名修改成自己的就行
