### ISSUE TITLE
IOS配置第6步出错的问题

### ISSUE THREAD

**Issue by papabattery** [songxiaoliang/react-native-share#36]
按照步骤接入，在编译时提示'UMSocialCore/UMSocialCore.h' file not found    在尝试了网上各种方法后还是没有解决，需要做什么处理吗？我不是做IOS开发的，这段时间刚开始学IOS的知识，对IOS的一些配置的处理还不是很懂。

**Comment by songxiaoliang** [comment]
@papabattery 应该是第三方依赖没有正确导入，你检查一下。
