### ISSUE TITLE
安卓实机分享遇到错误求解

### ISSUE THREAD

**Issue by rokurouC** [songxiaoliang/react-native-share#37]
我这着这篇https://blog.csdn.net/u013718120/article/details/75040805
实际做过一遍，App也都有注册，
iOS没有问题，但是安卓发起分享时会遇到错误，请问这个错误是什么原因，该如何排除呢？

Attempt to invoke interface method 'void com.umeng.commonsdk.debug.UMDebugLog.mutlInfo(java.lang.String, int, java.lang.String[])' on a null object reference
![screenshot_1535626951](https://user-images.githubusercontent.com/29245141/44847839-51ef4d80-ac87-11e8-9bae-58ee877fbadd.png)

**Comment by songxiaoliang** [comment]
@rokurouC 看起来像是在debug模式下运行的，sdk插件在分享时，是必须要在release环境下才可以。排查一下是不是这块的问题。

**Comment by rokurouC** [comment]
@songxiaoliang  还是不行呢，release调试是这样改吗
buildTypes {

  debug {
    .....
    signingConfig signingConfigs.release
  }

**Comment by songxiaoliang** [comment]
@rokurouC 这个问题应该是你没有注册Application导致的。

**Comment by rokurouC** [comment]
友盟的话有注册喔
http://dev.umeng.com/game_analytics/game-android/integration
是从这里获得APPkey的吗

**Comment by songxiaoliang** [comment]
@rokurouC 看reademe第九条
