### ISSUE TITLE
你的README的纯图片分享有问题,没有更新到位

### ISSUE THREAD

**Issue by RabbitJohn** [songxiaoliang/react-native-share#40]
README中是这样写的 NativeModules.sharemodule.shareImg(image.path, SharePlatform.WECHAT, (result)=>{
    });
iOS代码中的纯图片分享函数却是shareImage,请及时更新..

**Comment by songxiaoliang** [comment]
@RabbitJohn 已修复。

**Comment by RabbitJohn** [comment]
问题是iOS和android原生的函数名不一致额.说明文档改了以后android的小伙伴们是不是掉不通了呀😂
