### ISSUE TITLE
Android java错误: 找不到符号

### ISSUE THREAD

**Issue by jweboy** [songxiaoliang/react-native-share#5]
> /Users/jweboy/GitRepo/myReactNativeApp/android/app/src/main/java/com/reactnativeshare/MainActivity.java:7: 错误: 找不到符号
import com.reactnativeshare.module.ShareModule;
                                  ^
  符号:   类 ShareModule
  位置: 程序包 com.reactnativeshare.module
/Users/jweboy/GitRepo/myReactNativeApp/android/app/src/main/java/com/reactnativeshare/MainActivity.java:23: 错误: 找不到符号
        ShareModule.initActivity(this);
        ^
  符号:   变量 ShareModule
  位置: 类 MainActivity
/Users/jweboy/GitRepo/myReactNativeApp/android/app/src/main/java/com/reactnativeshare/MainApplication.java:23: 错误: 找不到符号
      return BuildConfig.DEBUG;
             ^
  符号: 变量 BuildConfig
/Users/jweboy/GitRepo/myReactNativeApp/android/app/src/main/java/com/reactnativeshare/module/SharePackage.java:22: 错误: 找不到符号
        modules.add(new ShareModule(reactContext));
                        ^
  符号:   类 ShareModule
  位置: 类 SharePackage
4 个错误
:app:compileDebugJavaWithJavac FAILED

关于这个编译问题该如何解决？

**Comment by songxiaoliang** [comment]
@jweboy 看下你这个路径是否正确 import com.reactnativeshare.module.ShareModule;  ShareModule所在的目录路径是否正确。
