### ISSUE TITLE
分享面板有空白，图标不显示，遇到吗

### ISSUE THREAD

**Issue by lxp-git** [songxiaoliang/react-native-share#8]
![231507774937_ pic](https://user-images.githubusercontent.com/7076832/31483171-e649b35c-aef0-11e7-889c-c05ca5aa7bed.jpg)

**Comment by songxiaoliang** [comment]
@wfly-git 这个应该是UI的问题，或者资源加载有问题，你可以卸载App，重新装一下。

**Comment by lxp-git** [comment]
谢谢，是没有加入资源文件，不是做 ios 开发的不懂。
